location /rpc/ {
    gzip off;
    root /var/www/cgi-bin;
    fastcgi_pass unix:/run/fcgiwrap/fcgiwrap-nginx.sock;
    fastcgi_index saludo.cgi;
    include /etc/nginx/fastcgi_params;
    fastcgi_param SCRIPT_FILENAME /var/www/cgi-bin$fastcgi_script_name;
}
